const en = {
    translation: {
        "\n\t\tsidebar\n\t\tlinks\n\t\tcalendar\n\t": "Calendar",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\tsunday\n\t": "Su",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\tmonday\n\t": "Mo",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\ttuesday\n\t": "Tu",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\twednesday\n\t": "We",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\tthursday\n\t": "Th",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\tfriday\n\t": "Fr",
        "\n\t\tcalendar\n\t\tdays-of-the-week\n\t\tsaturday\n\t": "Sa",
        "\n\t\tcalendar\n\t\theader\n\t\tjanuary\n\t": "JANUARY",
        "\n\t\tcalendar\n\t\theader\n\t\tfebruary\n\t": "FEBRUARY",
        "\n\t\tcalendar\n\t\theader\n\t\tmarch\n\t": "MARCH",
        "\n\t\tcalendar\n\t\theader\n\t\tapril\n\t": "APRIL",
        "\n\t\tcalendar\n\t\theader\n\t\tmay\n\t": "MAY",
        "\n\t\tcalendar\n\t\theader\n\t\tjune\n\t": "JUNE",
        "\n\t\tcalendar\n\t\theader\n\t\tjuly\n\t": "JULY",
        "\n\t\tcalendar\n\t\theader\n\t\taugust\n\t": "AUGUST",
        "\n\t\tcalendar\n\t\theader\n\t\tseptember\n\t": "SEPTEMBER",
        "\n\t\tcalendar\n\t\theader\n\t\toctober\n\t": "OCTOBER",
        "\n\t\tcalendar\n\t\theader\n\t\tnovember\n\t": "NOVEMBER",
        "\n\t\tcalendar\n\t\theader\n\t\tdecember\n\t": "DECEMBER",
        "\n\t\tcalendar\n\t\tnavigation\n\t\tnext\n\t": "Next",
        "\n\t\tcalendar\n\t\tnavigation\n\t\tprevious\n\t": "Prev",
        "\n\t\tto-do-list\n\t\theader\n\t": "To-do list",
        "\n\t\tto-do-list\n\t\tcreator\n\t\theader\n\t": "Header",
        "\n\t\tto-do-list\n\t\tcreator\n\t\tcontent\n\t": "Content",
        "\n\t\tto-do-list\n\t\tcreator\n\t\tbutton\n\t": "Create",
        "\n\t\tnot-found\n\t\theader\n\t": "Not found",
        "\n\t\tauth\n\t\tlogin\n\t\theader\n\t": "Login",
        "\n\t\tauth\n\t\tlogin\n\t\tlogin\n\t": "Enter your login",
        "\n\t\tauth\n\t\tlogin\n\t\tpassword\n\t": "Enter your password",
        "\n\t\tauth\n\t\tlogin\n\t\tsubmit\n\t": "Submit",
        "\n\t\tauth\n\t\tregister\n\t\theader\n\t": "Register",
        "\n\t\tauth\n\t\tregister\n\t\tname\n\t": "Enter your name",
        "\n\t\tauth\n\t\tregister\n\t\tlogin\n\t": "Enter your login",
        "\n\t\tauth\n\t\tregister\n\t\tpassword\n\t": "Enter your password",
        "\n\t\tauth\n\t\tregister\n\t\tsubmit\n\t": "Submit",
        "\n\t\theader\n\t\tprofile\n\t\tsign-out\n\t": "Sign out",
    }
}

export default en
